### ISSUE TITLE
Page titles and description meta tags

### ISSUE THREAD

**Issue by CatalinFrancu** [TeamDignitas/dignitas#284]
Currently we don't have description meta tags, so Google, Bing and DuckDuckGo show random snippets.

- [x] home page: meta tag should be configurable and translatable
- [x] statement page: page title should be *author name: summary | Dignitas*
- [x] statement page: meta tag should be the goal

Both the page title and the meta tag should have between 70 and 155 characters.
